use_half: False

# 智算中心训练路径
work_dir: /code/results/intermediate/
data_path: /code/results/result/lmdb/  # path/to/saved/lmdb
data_meta: /code/results/result/meta/train.json  #meta/train.json
# 本地训练路径
# work_dir: ./results/intermediate_shuffle_true/
# data_path: ./results/result/lmdb/  # path/to/saved/lmdb
# data_meta: ./results/result/meta/train.json  #meta/train.json
content_reference_json: ./meta/cr_mapping.json
content_font: "imgs"

input_size: 128
num_heads: 8
kshot: 5

batch_size: 32
n_workers: 6
iter: 200000
g_lr: 2e-4
d_lr: 4e-4 
step_size: 10000
gamma: 0.95
overwrite: False
adam_betas: [0.0, 0.9]

cv_n_unis: 15 # 30
cv_n_fonts: 9 # 10

print_freq: 100
val_freq: 5000
save_freq: 5000
tb_freq: 10000
